# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d65a8bec466ef441e71e35bd1225f700930674404281311dda1af17e34f396455a517e6e54203dd2ce005269b07929f031b9e0f5f242d55751b07fdaca1792f

test:
  secret_key_base: ff35b22a6b8201ddba88ae17895b70d87fa3b2fa49c10fa48f9bc14e4af1f6f50d4a5694f3fd1fd9f28afe3d0413700ac3ef4920870b4930530353e4824060ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
